
package detail;

import solver.PathCreator;

import java.util.List;

/**
 *
 * @author Albertus Kelvin
 */
public class DetailIMG extends javax.swing.JFrame {

    private List<PathCreator> fPC;
    private Integer[] matchID;
    
    /**
     * Creates new form DetailIMG
     * @param matchID valid permutation for creating the path
     */
    public DetailIMG(List<PathCreator> fPC, Integer[] matchID) {
        initComponents();
        
        disableEditing();
        
        this.fPC = fPC;
        this.matchID = matchID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_detailtitle = new javax.swing.JLabel();
        jPanel_detailmatrix = new javax.swing.JPanel();
        jText_detail00 = new javax.swing.JTextField();
        jText_detail01 = new javax.swing.JTextField();
        jText_detail02 = new javax.swing.JTextField();
        jText_detail03 = new javax.swing.JTextField();
        jText_detail10 = new javax.swing.JTextField();
        jText_detail11 = new javax.swing.JTextField();
        jText_detail12 = new javax.swing.JTextField();
        jText_detail13 = new javax.swing.JTextField();
        jText_detail20 = new javax.swing.JTextField();
        jText_detail21 = new javax.swing.JTextField();
        jText_detail22 = new javax.swing.JTextField();
        jText_detail23 = new javax.swing.JTextField();
        jText_detail30 = new javax.swing.JTextField();
        jText_detail31 = new javax.swing.JTextField();
        jText_detail32 = new javax.swing.JTextField();
        jText_detail33 = new javax.swing.JTextField();
        jButton_detailexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_detailtitle.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel_detailtitle.setText("DetailIMG");

        jPanel_detailmatrix.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matrix", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 24))); // NOI18N

        jText_detail00.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail01.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail02.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail03.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail10.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail11.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail12.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail13.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail20.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail21.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail22.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail23.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail30.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail31.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail32.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_detail33.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jText_detail33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel_detailmatrixLayout = new javax.swing.GroupLayout(jPanel_detailmatrix);
        jPanel_detailmatrix.setLayout(jPanel_detailmatrixLayout);
        jPanel_detailmatrixLayout.setHorizontalGroup(
            jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_detailmatrixLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_detailmatrixLayout.createSequentialGroup()
                        .addComponent(jText_detail30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jText_detail31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_detailmatrixLayout.createSequentialGroup()
                        .addComponent(jText_detail20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jText_detail21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_detailmatrixLayout.createSequentialGroup()
                        .addGroup(jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_detail00, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_detail10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jText_detail11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_detail01, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jText_detail02, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText_detail03, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel_detailmatrixLayout.setVerticalGroup(
            jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_detailmatrixLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_detail00, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail01, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail02, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail03, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_detail10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_detail20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel_detailmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_detail30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_detail33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jButton_detailexit.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton_detailexit.setText("Exit");
        jButton_detailexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_detailexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel_detailmatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel_detailtitle)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_detailexit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel_detailtitle)
                .addGap(29, 29, 29)
                .addComponent(jPanel_detailmatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton_detailexit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_detailexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_detailexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_detailexitActionPerformed

    private void disableEditing() {
        jText_detail00.setEditable(false);
        jText_detail01.setEditable(false);
        jText_detail02.setEditable(false);
        jText_detail03.setEditable(false);
        jText_detail10.setEditable(false);
        jText_detail11.setEditable(false);
        jText_detail12.setEditable(false);
        jText_detail13.setEditable(false);
        jText_detail20.setEditable(false);
        jText_detail21.setEditable(false);
        jText_detail22.setEditable(false);
        jText_detail23.setEditable(false);
        jText_detail30.setEditable(false);
        jText_detail31.setEditable(false);
        jText_detail32.setEditable(false);
        jText_detail33.setEditable(false);
    }
    
    private void setTextField(int dx, int dy, int ctr) {
        if (dx == 0 && dy == 0) {
            jText_detail00.setText(jText_detail00.getText() + Integer.toString(ctr));
        } else if (dx == 0 && dy == 1) {
            jText_detail01.setText(jText_detail01.getText() + Integer.toString(ctr));
        } else if (dx == 0 && dy == 2) {
            jText_detail02.setText(jText_detail02.getText() + Integer.toString(ctr));
        } else if (dx == 0 && dy == 3) {
            jText_detail03.setText(jText_detail03.getText() + Integer.toString(ctr));
        } else if (dx == 1 && dy == 0) {
            jText_detail10.setText(jText_detail10.getText() + Integer.toString(ctr));
        } else if (dx == 1 && dy == 1) {
            jText_detail11.setText(jText_detail11.getText() + Integer.toString(ctr));
        } else if (dx == 1 && dy == 2) {
            jText_detail12.setText(jText_detail12.getText() + Integer.toString(ctr));
        } else if (dx == 1 && dy == 3) {
            jText_detail13.setText(jText_detail13.getText() + Integer.toString(ctr));
        } else if (dx == 2 && dy == 0) {
            jText_detail20.setText(jText_detail20.getText() + Integer.toString(ctr));
        } else if (dx == 2 && dy == 1) {
            jText_detail21.setText(jText_detail21.getText() + Integer.toString(ctr));
        } else if (dx == 2 && dy == 2) {
            jText_detail22.setText(jText_detail22.getText() + Integer.toString(ctr));
        } else if (dx == 2 && dy == 3) {
            jText_detail23.setText(jText_detail23.getText() + Integer.toString(ctr));
        } else if (dx == 3 && dy == 0) {
            jText_detail30.setText(jText_detail30.getText() + Integer.toString(ctr));
        } else if (dx == 3 && dy == 1) {
            jText_detail31.setText(jText_detail31.getText() + Integer.toString(ctr));
        } else if (dx == 3 && dy == 2) {
            jText_detail32.setText(jText_detail32.getText() + Integer.toString(ctr));
        } else if (dx == 3 && dy == 3) {
            jText_detail33.setText(jText_detail33.getText() + Integer.toString(ctr));
        } 
    }
    
    public void showHowTo() {
        
        // KAMUS
        int counter = 0;
        int xx, yy;
        
        // ALGORITMA
        for (Integer elmt : matchID) {
            xx = fPC.get(elmt).idx;
            yy = fPC.get(elmt).idy;
            
            counter++;
            setTextField(xx, yy, counter);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_detailexit;
    private javax.swing.JLabel jLabel_detailtitle;
    private javax.swing.JPanel jPanel_detailmatrix;
    private javax.swing.JTextField jText_detail00;
    private javax.swing.JTextField jText_detail01;
    private javax.swing.JTextField jText_detail02;
    private javax.swing.JTextField jText_detail03;
    private javax.swing.JTextField jText_detail10;
    private javax.swing.JTextField jText_detail11;
    private javax.swing.JTextField jText_detail12;
    private javax.swing.JTextField jText_detail13;
    private javax.swing.JTextField jText_detail20;
    private javax.swing.JTextField jText_detail21;
    private javax.swing.JTextField jText_detail22;
    private javax.swing.JTextField jText_detail23;
    private javax.swing.JTextField jText_detail30;
    private javax.swing.JTextField jText_detail31;
    private javax.swing.JTextField jText_detail32;
    private javax.swing.JTextField jText_detail33;
    // End of variables declaration//GEN-END:variables
}
