
package home;

/**
 *
 * @author Albertus Kelvin
 */
public class gamerules extends javax.swing.JFrame {

    /**
     * Creates new form gamerules
     */
    public gamerules() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_title = new javax.swing.JLabel();
        jPanel_rules = new javax.swing.JPanel();
        jLabel_rules1a = new javax.swing.JLabel();
        jLabel_rules1b = new javax.swing.JLabel();
        jLabel_rules2a = new javax.swing.JLabel();
        jLabel_rules2b = new javax.swing.JLabel();
        jLabel_rules3a = new javax.swing.JLabel();
        jLabel_rules4a = new javax.swing.JLabel();
        jLabel_rules4b = new javax.swing.JLabel();
        jLabel_rules0a = new javax.swing.JLabel();
        jButton_next = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_title.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel_title.setText("Wordament Solver");

        jPanel_rules.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rules", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 18))); // NOI18N

        jLabel_rules1a.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel_rules1a.setText("1. Wordament hanya memiliki satu karakter di setiap selnya,");

        jLabel_rules1b.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel_rules1b.setText(" tidak mengimplementasi kemungkinan dua karakter");

        jLabel_rules2a.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel_rules2a.setText("2. Program dapat mencari sebanyak mungkin kata pada wordament");

        jLabel_rules2b.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel_rules2b.setText(" yang cocok dengan kamus");

        jLabel_rules3a.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel_rules3a.setText("3. Setiap karakter dihitung sebagai satu poin");

        jLabel_rules4a.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel_rules4a.setText("4. Setiap kata yang sudah ditebak oleh program perlu ditampilkan di GUI");

        jLabel_rules4b.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel_rules4b.setText(" beserta skornya");

        jLabel_rules0a.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel_rules0a.setText("0. Program memiliki struktur data matriks 4x4 (character)");

        javax.swing.GroupLayout jPanel_rulesLayout = new javax.swing.GroupLayout(jPanel_rules);
        jPanel_rules.setLayout(jPanel_rulesLayout);
        jPanel_rulesLayout.setHorizontalGroup(
            jPanel_rulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_rulesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel_rulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_rules0a)
                    .addComponent(jLabel_rules4a)
                    .addComponent(jLabel_rules3a)
                    .addComponent(jLabel_rules2a)
                    .addComponent(jLabel_rules1a, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_rulesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel_rulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_rules2b)
                            .addComponent(jLabel_rules4b)
                            .addComponent(jLabel_rules1b, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel_rulesLayout.setVerticalGroup(
            jPanel_rulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_rulesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_rules0a)
                .addGap(18, 18, 18)
                .addComponent(jLabel_rules1a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_rules1b)
                .addGap(18, 18, 18)
                .addComponent(jLabel_rules2a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_rules2b)
                .addGap(18, 18, 18)
                .addComponent(jLabel_rules3a)
                .addGap(18, 18, 18)
                .addComponent(jLabel_rules4a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_rules4b)
                .addGap(51, 51, 51))
        );

        jButton_next.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton_next.setText("Next");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel_rules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_title)
                .addGap(180, 180, 180))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel_title)
                .addGap(42, 42, 42)
                .addComponent(jPanel_rules, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
        String[] args = {};
        
        board.main(args);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gamerules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gamerules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gamerules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gamerules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gamerules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_rules0a;
    private javax.swing.JLabel jLabel_rules1a;
    private javax.swing.JLabel jLabel_rules1b;
    private javax.swing.JLabel jLabel_rules2a;
    private javax.swing.JLabel jLabel_rules2b;
    private javax.swing.JLabel jLabel_rules3a;
    private javax.swing.JLabel jLabel_rules4a;
    private javax.swing.JLabel jLabel_rules4b;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel_rules;
    // End of variables declaration//GEN-END:variables
}
