package wordamentsolver;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MJ
 */
public class WordamentSolver extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public WordamentSolver() {
        initComponents();
    }
    
    /**
     * Variables
     */
    private char box[][] = new char[4][4];
    private Timer t;
    private int second = 0;
    private int minute = 0;
    private int score = 0;
    private Integer num = 0;
    private Object[] row = new Object[2];
    private Set<String> wordsFound = new HashSet<String>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Box_9 = new javax.swing.JTextField();
        Box_11 = new javax.swing.JTextField();
        Box_10 = new javax.swing.JTextField();
        Box_3 = new javax.swing.JTextField();
        Box_6 = new javax.swing.JTextField();
        Box_2 = new javax.swing.JTextField();
        Box_5 = new javax.swing.JTextField();
        Box_1 = new javax.swing.JTextField();
        Box_7 = new javax.swing.JTextField();
        Box_13 = new javax.swing.JTextField();
        Box_4 = new javax.swing.JTextField();
        Box_15 = new javax.swing.JTextField();
        Box_14 = new javax.swing.JTextField();
        Box_12 = new javax.swing.JTextField();
        Box_16 = new javax.swing.JTextField();
        Box_8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Start_Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Start_Btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Timer_Minute = new javax.swing.JTextField();
        Timer_Second = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(100, 100));
        setLocationByPlatform(true);
        setName("WordamentSolver"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(481, 375));

        jPanel2.setBackground(new java.awt.Color(60, 169, 163));

        Box_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_9ActionPerformed(evt);
            }
        });
        Box_9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_9KeyTyped(evt);
            }
        });

        Box_11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_11ActionPerformed(evt);
            }
        });
        Box_11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_11KeyTyped(evt);
            }
        });

        Box_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_10ActionPerformed(evt);
            }
        });
        Box_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_10KeyTyped(evt);
            }
        });

        Box_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_3ActionPerformed(evt);
            }
        });
        Box_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_3KeyTyped(evt);
            }
        });

        Box_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_6ActionPerformed(evt);
            }
        });
        Box_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_6KeyTyped(evt);
            }
        });

        Box_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_2ActionPerformed(evt);
            }
        });
        Box_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_2KeyTyped(evt);
            }
        });

        Box_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_5ActionPerformed(evt);
            }
        });
        Box_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_5KeyTyped(evt);
            }
        });

        Box_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_1ActionPerformed(evt);
            }
        });
        Box_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_1KeyTyped(evt);
            }
        });

        Box_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_7ActionPerformed(evt);
            }
        });
        Box_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_7KeyTyped(evt);
            }
        });

        Box_13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_13ActionPerformed(evt);
            }
        });
        Box_13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_13KeyTyped(evt);
            }
        });

        Box_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_4ActionPerformed(evt);
            }
        });
        Box_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_4KeyTyped(evt);
            }
        });

        Box_15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_15ActionPerformed(evt);
            }
        });
        Box_15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_15KeyTyped(evt);
            }
        });

        Box_14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_14ActionPerformed(evt);
            }
        });
        Box_14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_14KeyTyped(evt);
            }
        });

        Box_12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_12ActionPerformed(evt);
            }
        });
        Box_12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_12KeyTyped(evt);
            }
        });

        Box_16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_16ActionPerformed(evt);
            }
        });
        Box_16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_16KeyTyped(evt);
            }
        });

        Box_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_8ActionPerformed(evt);
            }
        });
        Box_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_8KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Box_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box_10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box_11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Box_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Box_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Box_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Box_13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box_14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box_15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Box_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box_13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter the word below :");

        Start_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Start_Btn.setFont(new java.awt.Font("Alcubierre", 0, 18)); // NOI18N
        Start_Btn.setForeground(new java.awt.Color(102, 102, 102));
        Start_Btn.setText("START");
        Start_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Start_Btn.setBorderPainted(false);
        Start_Btn.setContentAreaFilled(false);
        Start_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Start_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Start_Btn.setOpaque(true);
        Start_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Start_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Start_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Start_BtnMousePressed(evt);
            }
        });
        Start_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_BtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Word"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setSelectionBackground(new java.awt.Color(60, 169, 163));
        jTable1.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Result :");

        Start_Btn1.setBackground(new java.awt.Color(255, 255, 255));
        Start_Btn1.setFont(new java.awt.Font("Alcubierre", 0, 12)); // NOI18N
        Start_Btn1.setForeground(new java.awt.Color(102, 102, 102));
        Start_Btn1.setText("AGAIN?");
        Start_Btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Start_Btn1.setBorderPainted(false);
        Start_Btn1.setContentAreaFilled(false);
        Start_Btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Start_Btn1.setEnabled(false);
        Start_Btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Start_Btn1.setOpaque(true);
        Start_Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Start_Btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Start_Btn1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Start_Btn1MousePressed(evt);
            }
        });
        Start_Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_Btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Start_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Start_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Start_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.getAccessibleContext().setAccessibleName("Resullt");

        jLabel1.setFont(new java.awt.Font("Alcubierre", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("WordamentSolver!");

        Timer_Minute.setEditable(false);
        Timer_Minute.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Timer_Minute.setForeground(new java.awt.Color(51, 51, 51));
        Timer_Minute.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Timer_Minute.setText("00");
        Timer_Minute.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 169, 163)));
        Timer_Minute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Timer_MinuteActionPerformed(evt);
            }
        });

        Timer_Second.setEditable(false);
        Timer_Second.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Timer_Second.setForeground(new java.awt.Color(51, 51, 51));
        Timer_Second.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Timer_Second.setText("00");
        Timer_Second.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 169, 163)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 196, 163));
        jLabel3.setText(":");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wordamentsolver/close.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/wordamentsolver/close_hover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Alcubierre", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("SCORE");

        jLabel5.setFont(new java.awt.Font("Alcubierre", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("TIMER");

        Score.setFont(new java.awt.Font("Alcubierre", 0, 32)); // NOI18N
        Score.setForeground(new java.awt.Color(102, 102, 102));
        Score.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Timer_Minute, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Timer_Second, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Timer_Second, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(Score))
                    .addComponent(Timer_Minute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Box_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_11ActionPerformed

    private void Box_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_1ActionPerformed

    private void Box_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_6ActionPerformed

    private void Box_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_5ActionPerformed

    private void Box_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_9ActionPerformed

    private void Box_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_7ActionPerformed

    private void Box_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_10ActionPerformed

    private void Box_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_3ActionPerformed

    private void Box_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_2ActionPerformed

    private void Box_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_13ActionPerformed

    private void Box_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_4ActionPerformed

    private void Box_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_15ActionPerformed

    private void Box_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_14ActionPerformed

    private void Box_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_12ActionPerformed

    private void Box_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_16ActionPerformed

    private void Box_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_8ActionPerformed

    private void Start_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_BtnActionPerformed
        if ("".equals(Box_1.getText()) || "".equals(Box_2.getText()) || 
                "".equals(Box_3.getText())  || "".equals(Box_4.getText()) ||
                "".equals(Box_5.getText()) || "".equals(Box_6.getText()) ||
                "".equals(Box_7.getText()) || "".equals(Box_8.getText()) || 
                "".equals(Box_9.getText())  || "".equals(Box_10.getText()) ||
                "".equals(Box_11.getText()) || "".equals(Box_12.getText()) ||
                "".equals(Box_13.getText()) || "".equals(Box_14.getText()) || 
                "".equals(Box_15.getText())  || "".equals(Box_16.getText())) {
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Fill All The Box", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else {
            Start_Btn.setEnabled(false);
            Start_Btn.setVisible(false);
            //Get each bx char
            box[0][0] = Box_1.getText().charAt(0);
            box[0][1] = Box_2.getText().charAt(0);
            box[0][2] = Box_3.getText().charAt(0);
            box[0][3] = Box_4.getText().charAt(0);
            box[1][0] = Box_5.getText().charAt(0);
            box[1][1] = Box_6.getText().charAt(0);
            box[1][2] = Box_7.getText().charAt(0);
            box[1][3] = Box_8.getText().charAt(0);
            box[2][0] = Box_9.getText().charAt(0);
            box[2][1] = Box_10.getText().charAt(0);
            box[2][2] = Box_11.getText().charAt(0);
            box[2][3] = Box_12.getText().charAt(0);
            box[3][0] = Box_13.getText().charAt(0);
            box[3][1] = Box_14.getText().charAt(0);
            box[3][2] = Box_15.getText().charAt(0);
            box[3][3] = Box_16.getText().charAt(0);
            
            //Make te box unable to edit
            Box_1.setEnabled(false);
            Box_2.setEnabled(false);
            Box_3.setEnabled(false);
            Box_4.setEnabled(false);
            Box_5.setEnabled(false);
            Box_6.setEnabled(false);
            Box_7.setEnabled(false);
            Box_8.setEnabled(false);
            Box_9.setEnabled(false);
            Box_10.setEnabled(false);
            Box_11.setEnabled(false);
            Box_12.setEnabled(false);
            Box_13.setEnabled(false);
            Box_14.setEnabled(false);
            Box_15.setEnabled(false);
            Box_16.setEnabled(false);
            
            //Timer
            t = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    second++;
                    if (second == 60) {
                        minute++;
                        second = 0;
                    }
                    
                    Timer_Minute.setText("0" + minute);
                    if (second<10) {
                        Timer_Second.setText("0" + second);
                    }
                    else {
                        Timer_Second.setText(second + "");
                    }
                }
            });
            
            t.start();
           
            //Get Relative Path
            URL url = getClass().getResource("dictionary.txt");

            DictReader dictionary;
            dictionary = new DictReader(convertPath(url.getPath()));;
            
            try {
                dictionary.processLineByLine();
            } catch (IOException ex) {
                Logger.getLogger(WordamentSolver.class.getName()).log(Level.SEVERE, null, ex);
            }
            Tree kamus = dictionary.getTree();
         
            for (int i = 0; i < 4; i++) {
                for (int j = 0; j < 4; j++) {
                    checkBox(box, new boolean[4][4], i, j, kamus, "");
                }
            }
            
            List<String> listWord = new ArrayList<String>(wordsFound);
            
            listWord.stream().map((word) -> {
                num++;
                return word;
            }).map((word) -> {
                score = score + word.length();
                return word;
            }).map((word) -> {
                row[0] = num;
                return word;
            }).map((word) -> {
                row[1] = word;
                return word;
            }).map((_item) -> (DefaultTableModel) jTable1.getModel()).forEach((model) -> {
                model.addRow(row);
            });
            
            Score.setText(score + "");
            Start_Btn1.setVisible(true);
            Start_Btn1.setEnabled(true);
        }
    }//GEN-LAST:event_Start_BtnActionPerformed
    
     /**
     * @param Path path string need to be converted
     * @return string
     */
    private String convertPath (String Path) {
        String Temp = "";
        
        Temp = Temp + Path.charAt(1) + ":\\";
        for (int i=3;i<Path.length();i++) {
            if (Path.charAt(i) == '/') {
                Temp = Temp + "\\";
            }
            else {
                Temp = Temp + Path.charAt(i);
            }
        }
        
        return Temp;
    }
    
    private void Start_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Start_BtnMouseEntered
        Start_Btn.setForeground(new java.awt.Color(60, 169, 163));
    }//GEN-LAST:event_Start_BtnMouseEntered

    private void Start_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Start_BtnMousePressed
        
    }//GEN-LAST:event_Start_BtnMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Box_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_1KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_1.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_1KeyTyped

    private void Box_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_2KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_2.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_2KeyTyped

    private void Box_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_3KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_3.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_3KeyTyped

    private void Box_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_4KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_4.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_4KeyTyped

    private void Box_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_5KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_5.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_5KeyTyped

    private void Box_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_6KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_6.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_6KeyTyped

    private void Box_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_7KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_7.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_7KeyTyped

    private void Box_8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_8KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_8.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_8KeyTyped

    private void Box_9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_9KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_9.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_9KeyTyped

    private void Box_10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_10KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_10.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_10KeyTyped

    private void Box_11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_11KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_11.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_11KeyTyped

    private void Box_12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_12KeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_12.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_12KeyTyped

    private void Box_13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_13KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_13.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_13KeyTyped

    private void Box_14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_14KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_14.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_14KeyTyped

    private void Box_15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_15KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_15.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_15KeyTyped

    private void Box_16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_16KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_16.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_16KeyTyped

    private void Timer_MinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Timer_MinuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Timer_MinuteActionPerformed

    private void Start_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Start_BtnMouseExited
        Start_Btn.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_Start_BtnMouseExited

    private void Start_Btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Start_Btn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Start_Btn1MouseEntered

    private void Start_Btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Start_Btn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Start_Btn1MouseExited

    private void Start_Btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Start_Btn1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Start_Btn1MousePressed

    private void Start_Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_Btn1ActionPerformed
        //Make te box able to edit
            Box_1.setEnabled(true);
            Box_2.setEnabled(true);
            Box_3.setEnabled(true);
            Box_4.setEnabled(true);
            Box_5.setEnabled(true);
            Box_6.setEnabled(true);
            Box_7.setEnabled(true);
            Box_8.setEnabled(true);
            Box_9.setEnabled(true);
            Box_10.setEnabled(true);
            Box_11.setEnabled(true);
            Box_12.setEnabled(true);
            Box_13.setEnabled(true);
            Box_14.setEnabled(true);
            Box_15.setEnabled(true);
            Box_16.setEnabled(true);
            Start_Btn.setEnabled(true);
            Start_Btn.setVisible(true);
            Start_Btn1.setVisible(false);
            DefaultTableModel model = (DefaultTableModel)this.jTable1.getModel();
            model.setRowCount(0);
            t.stop();
            second = 0;
            minute = 0;
            Timer_Second.setText("00");
            Timer_Minute.setText("00");
            Score.setText("0");
            num = 0;
            score = 0;
    }//GEN-LAST:event_Start_Btn1ActionPerformed
    
    /**
     * @param box matrix of char
     * @param visited matrix which show the char has visited or not
     * @param i current position x
     * @param j current position y
     * @param node current tree that have visited
     * @param currentWord current working word
     */
    private void checkBox(char[][] box, boolean[][] visited, int i, int j, Tree node, String currentWord) {
        char c = box[i][j];
        String newWord;
        newWord = currentWord + Character.toString(c);
        Tree nextChar;
        try {
            nextChar = node.getNode(c);
        }
        catch (NullPointerException e) {
            nextChar = null;
        }

        if (nextChar != null) {
            visited[i][j] = true;
            if (nextChar.isWord()) {
                wordsFound.add(newWord);
            }

            if (i > 0 && !visited[i - 1][j]) {
                checkBox(box, visited, i - 1, j, nextChar, newWord);
            }
            if (i < 3 && !visited[i + 1][j]) {
                checkBox(box, visited, i + 1, j, nextChar, newWord);
            }
            if (j > 0 && !visited[i][j - 1]) {
                checkBox(box, visited, i, j - 1, nextChar, newWord);
            }
            if (j < 3 && !visited[i][j + 1]) {
                checkBox(box, visited, i, j + 1, nextChar, newWord);
            }
            if (i < 3 && j < 3 && !visited[i + 1][j + 1]) {
                checkBox(box, visited, i + 1, j + 1, nextChar, newWord);
            }
            if (i < 3 && j > 0 && !visited[i + 1][j - 1]) {
                checkBox(box, visited, i + 1, j - 1, nextChar, newWord);
            }
            if (i > 0 && j > 0 && !visited[i - 1][j - 1]) {
                checkBox(box, visited, i - 1, j - 1, nextChar, newWord);
            }
            if (i > 0 && j < 3 && !visited[i - 1][j + 1]) {
                checkBox(box, visited, i - 1, j + 1, nextChar, newWord);
            }
            visited[i][j] = false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordamentSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordamentSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordamentSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordamentSolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordamentSolver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Box_1;
    private javax.swing.JTextField Box_10;
    private javax.swing.JTextField Box_11;
    private javax.swing.JTextField Box_12;
    private javax.swing.JTextField Box_13;
    private javax.swing.JTextField Box_14;
    private javax.swing.JTextField Box_15;
    private javax.swing.JTextField Box_16;
    private javax.swing.JTextField Box_2;
    private javax.swing.JTextField Box_3;
    private javax.swing.JTextField Box_4;
    private javax.swing.JTextField Box_5;
    private javax.swing.JTextField Box_6;
    private javax.swing.JTextField Box_7;
    private javax.swing.JTextField Box_8;
    private javax.swing.JTextField Box_9;
    private javax.swing.JLabel Score;
    private javax.swing.JButton Start_Btn;
    private javax.swing.JButton Start_Btn1;
    private javax.swing.JTextField Timer_Minute;
    private javax.swing.JTextField Timer_Second;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
