/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

/**
 *
 * @author USER
 */
public class WordamentSolverMenu extends javax.swing.JFrame {

    /**
     * Creates new form WordamentSolverMenu
     */
    public WordamentSolverMenu() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bevelBorder1 = (javax.swing.border.BevelBorder)javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED);
        jBoardPanel = new javax.swing.JPanel();
        jTile1 = new javax.swing.JTextField();
        jTile2 = new javax.swing.JTextField();
        jTile3 = new javax.swing.JTextField();
        jTile7 = new javax.swing.JTextField();
        jTile6 = new javax.swing.JTextField();
        jTile5 = new javax.swing.JTextField();
        jTile9 = new javax.swing.JTextField();
        jTile10 = new javax.swing.JTextField();
        jTile11 = new javax.swing.JTextField();
        jTile4 = new javax.swing.JTextField();
        jTile8 = new javax.swing.JTextField();
        jTile12 = new javax.swing.JTextField();
        jTile16 = new javax.swing.JTextField();
        jTile15 = new javax.swing.JTextField();
        jTile14 = new javax.swing.JTextField();
        jTile13 = new javax.swing.JTextField();
        jBoardLabel = new java.awt.Label();
        jTestButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBoardPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTile1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile1.setText("X");
        jTile1.setBorder(new javax.swing.border.MatteBorder(null));

        jTile2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile2.setText("X");
        jTile2.setBorder(new javax.swing.border.MatteBorder(null));

        jTile3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile3.setText("X");
        jTile3.setBorder(new javax.swing.border.MatteBorder(null));

        jTile7.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile7.setText("X");
        jTile7.setBorder(new javax.swing.border.MatteBorder(null));

        jTile6.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile6.setText("X");
        jTile6.setBorder(new javax.swing.border.MatteBorder(null));

        jTile5.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile5.setText("X");
        jTile5.setBorder(new javax.swing.border.MatteBorder(null));

        jTile9.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile9.setText("X");
        jTile9.setBorder(new javax.swing.border.MatteBorder(null));

        jTile10.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile10.setText("X");
        jTile10.setBorder(new javax.swing.border.MatteBorder(null));

        jTile11.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile11.setText("X");
        jTile11.setBorder(new javax.swing.border.MatteBorder(null));

        jTile4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile4.setText("X");
        jTile4.setBorder(new javax.swing.border.MatteBorder(null));

        jTile8.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile8.setText("X");
        jTile8.setBorder(new javax.swing.border.MatteBorder(null));

        jTile12.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile12.setText("X");
        jTile12.setBorder(new javax.swing.border.MatteBorder(null));

        jTile16.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile16.setText("X");
        jTile16.setBorder(new javax.swing.border.MatteBorder(null));

        jTile15.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile15.setText("X");
        jTile15.setBorder(new javax.swing.border.MatteBorder(null));

        jTile14.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile14.setText("X");
        jTile14.setBorder(new javax.swing.border.MatteBorder(null));

        jTile13.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jTile13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTile13.setText("X");
        jTile13.setBorder(new javax.swing.border.MatteBorder(null));

        jBoardLabel.setAlignment(java.awt.Label.CENTER);
        jBoardLabel.setText("Wordament Board");

        javax.swing.GroupLayout jBoardPanelLayout = new javax.swing.GroupLayout(jBoardPanel);
        jBoardPanel.setLayout(jBoardPanelLayout);
        jBoardPanelLayout.setHorizontalGroup(
            jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBoardPanelLayout.createSequentialGroup()
                        .addGroup(jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTile1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTile5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTile9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTile2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTile6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTile10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTile3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTile7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTile11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTile4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTile8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTile12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jBoardPanelLayout.createSequentialGroup()
                        .addComponent(jTile13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTile14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTile15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTile16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jBoardLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jBoardPanelLayout.setVerticalGroup(
            jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBoardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBoardPanelLayout.createSequentialGroup()
                        .addComponent(jTile4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTile8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTile12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBoardPanelLayout.createSequentialGroup()
                        .addComponent(jTile3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTile7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTile11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jBoardPanelLayout.createSequentialGroup()
                            .addComponent(jTile2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTile6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTile10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jBoardPanelLayout.createSequentialGroup()
                            .addComponent(jTile1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTile5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTile9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTile16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTile15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTile14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTile13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTestButton.setText("SCIENCE");
        jTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTestButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTestButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(WordamentSolverMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(WordamentSolverMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(WordamentSolverMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(WordamentSolverMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new WordamentSolverMenu().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.border.BevelBorder bevelBorder1;
    private java.awt.Label jBoardLabel;
    private javax.swing.JPanel jBoardPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jTestButton;
    private javax.swing.JTextField jTile1;
    private javax.swing.JTextField jTile10;
    private javax.swing.JTextField jTile11;
    private javax.swing.JTextField jTile12;
    private javax.swing.JTextField jTile13;
    private javax.swing.JTextField jTile14;
    private javax.swing.JTextField jTile15;
    private javax.swing.JTextField jTile16;
    private javax.swing.JTextField jTile2;
    private javax.swing.JTextField jTile3;
    private javax.swing.JTextField jTile4;
    private javax.swing.JTextField jTile5;
    private javax.swing.JTextField jTile6;
    private javax.swing.JTextField jTile7;
    private javax.swing.JTextField jTile8;
    private javax.swing.JTextField jTile9;
    // End of variables declaration//GEN-END:variables
}
