package wordamentsolver;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author MJ
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    
    /**
     * Vaariables
     */
    char box[][] = new char[4][4];
    Timer t;
    int second = 0;
    int minute = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Box_9 = new javax.swing.JTextField();
        Box_11 = new javax.swing.JTextField();
        Box_10 = new javax.swing.JTextField();
        Box_3 = new javax.swing.JTextField();
        Box_6 = new javax.swing.JTextField();
        Box_2 = new javax.swing.JTextField();
        Box_5 = new javax.swing.JTextField();
        Box_1 = new javax.swing.JTextField();
        Box_7 = new javax.swing.JTextField();
        Box_13 = new javax.swing.JTextField();
        Box_4 = new javax.swing.JTextField();
        Box_15 = new javax.swing.JTextField();
        Box_14 = new javax.swing.JTextField();
        Box_12 = new javax.swing.JTextField();
        Box_16 = new javax.swing.JTextField();
        Box_8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Timer_Second = new javax.swing.JTextField();
        Timer_Minute = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(60, 169, 163));

        Box_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_9ActionPerformed(evt);
            }
        });
        Box_9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_9KeyTyped(evt);
            }
        });

        Box_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_11ActionPerformed(evt);
            }
        });
        Box_11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_11KeyTyped(evt);
            }
        });

        Box_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_10ActionPerformed(evt);
            }
        });
        Box_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_10KeyTyped(evt);
            }
        });

        Box_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_3ActionPerformed(evt);
            }
        });
        Box_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_3KeyTyped(evt);
            }
        });

        Box_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_6ActionPerformed(evt);
            }
        });
        Box_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_6KeyTyped(evt);
            }
        });

        Box_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_2ActionPerformed(evt);
            }
        });
        Box_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_2KeyTyped(evt);
            }
        });

        Box_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_5ActionPerformed(evt);
            }
        });
        Box_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_5KeyTyped(evt);
            }
        });

        Box_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_1ActionPerformed(evt);
            }
        });
        Box_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_1KeyTyped(evt);
            }
        });

        Box_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_7ActionPerformed(evt);
            }
        });
        Box_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_7KeyTyped(evt);
            }
        });

        Box_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_13ActionPerformed(evt);
            }
        });
        Box_13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_13KeyTyped(evt);
            }
        });

        Box_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_4ActionPerformed(evt);
            }
        });
        Box_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_4KeyTyped(evt);
            }
        });

        Box_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_15ActionPerformed(evt);
            }
        });
        Box_15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_15KeyTyped(evt);
            }
        });

        Box_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_14ActionPerformed(evt);
            }
        });
        Box_14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_14KeyTyped(evt);
            }
        });

        Box_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_12ActionPerformed(evt);
            }
        });
        Box_12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_12KeyTyped(evt);
            }
        });

        Box_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_16ActionPerformed(evt);
            }
        });
        Box_16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_16KeyTyped(evt);
            }
        });

        Box_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_8ActionPerformed(evt);
            }
        });
        Box_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Box_8KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Box_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box_10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box_11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Box_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Box_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Box_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Box_13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box_14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box_15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Box_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box_13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Alcubierre", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter the word below :");

        jButton1.setBackground(new java.awt.Color(60, 169, 163));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("START");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        Timer_Second.setText("00");

        Timer_Minute.setText("00");
        Timer_Minute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Timer_MinuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Timer_Minute, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Timer_Second, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Timer_Second, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Timer_Minute, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );

        jLabel1.setFont(new java.awt.Font("Alcubierre", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("WordamentSolver!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Box_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_11ActionPerformed

    private void Box_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_1ActionPerformed

    private void Box_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_6ActionPerformed

    private void Box_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_5ActionPerformed

    private void Box_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_9ActionPerformed

    private void Box_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_7ActionPerformed

    private void Box_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_10ActionPerformed

    private void Box_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_3ActionPerformed

    private void Box_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_2ActionPerformed

    private void Box_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_13ActionPerformed

    private void Box_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_4ActionPerformed

    private void Box_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_15ActionPerformed

    private void Box_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_14ActionPerformed

    private void Box_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_12ActionPerformed

    private void Box_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_16ActionPerformed

    private void Box_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ("".equals(Box_1.getText()) || "".equals(Box_2.getText()) || 
                "".equals(Box_3.getText())  || "".equals(Box_4.getText()) ||
                "".equals(Box_5.getText()) || "".equals(Box_6.getText()) ||
                "".equals(Box_7.getText()) || "".equals(Box_8.getText()) || 
                "".equals(Box_9.getText())  || "".equals(Box_10.getText()) ||
                "".equals(Box_11.getText()) || "".equals(Box_12.getText()) ||
                "".equals(Box_13.getText()) || "".equals(Box_14.getText()) || 
                "".equals(Box_15.getText())  || "".equals(Box_16.getText())) {
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Fill All The Box", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else {
            box[0][0] = Box_1.getText().charAt(0);
            box[0][1] = Box_2.getText().charAt(0);
            box[0][2] = Box_3.getText().charAt(0);
            box[0][3] = Box_4.getText().charAt(0);
            box[1][0] = Box_5.getText().charAt(0);
            box[1][1] = Box_6.getText().charAt(0);
            box[1][2] = Box_7.getText().charAt(0);
            box[1][3] = Box_8.getText().charAt(0);
            box[2][0] = Box_9.getText().charAt(0);
            box[2][1] = Box_10.getText().charAt(0);
            box[2][2] = Box_11.getText().charAt(0);
            box[2][3] = Box_12.getText().charAt(0);
            box[3][0] = Box_13.getText().charAt(0);
            box[3][1] = Box_14.getText().charAt(0);
            box[3][2] = Box_15.getText().charAt(0);
            box[3][3] = Box_16.getText().charAt(0);
            
            t = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    second++;
                    if (second == 60) {
                        minute++;
                        second = 0;
                    }
                    
                    Timer_Minute.setText("0" + minute);
                    if (second<10) {
                        Timer_Second.setText("0" + second);
                    }
                    else {
                        Timer_Second.setText(second + "");
                    }
                }
            });
            t.start();
        }
        
        String coba = "";
        
        for (int i=0;i<4;i++){
            for (int j=0;j<4;j++) {
                coba = coba + " " + box[i][j];
            }
        }
        jTextField1.setText(coba);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Box_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_1KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_1.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_1KeyTyped

    private void Box_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_2KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_2.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_2KeyTyped

    private void Box_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_3KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_3.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_3KeyTyped

    private void Box_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_4KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_4.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_4KeyTyped

    private void Box_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_5KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_5.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_5KeyTyped

    private void Box_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_6KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_6.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_6KeyTyped

    private void Box_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_7KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_7.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_7KeyTyped

    private void Box_8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_8KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_8.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_8KeyTyped

    private void Box_9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_9KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_9.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_9KeyTyped

    private void Box_10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_10KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_10.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_10KeyTyped

    private void Box_11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_11KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_11.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_11KeyTyped

    private void Box_12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_12KeyTyped
       char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_12.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_12KeyTyped

    private void Box_13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_13KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_13.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_13KeyTyped

    private void Box_14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_14KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_14.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_14KeyTyped

    private void Box_15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_15KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_15.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_15KeyTyped

    private void Box_16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Box_16KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
        
        String d = Box_16.getText();
        if (d.length() >= 1) {
            evt.consume();
        } 
    }//GEN-LAST:event_Box_16KeyTyped

    private void Timer_MinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Timer_MinuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Timer_MinuteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Box_1;
    private javax.swing.JTextField Box_10;
    private javax.swing.JTextField Box_11;
    private javax.swing.JTextField Box_12;
    private javax.swing.JTextField Box_13;
    private javax.swing.JTextField Box_14;
    private javax.swing.JTextField Box_15;
    private javax.swing.JTextField Box_16;
    private javax.swing.JTextField Box_2;
    private javax.swing.JTextField Box_3;
    private javax.swing.JTextField Box_4;
    private javax.swing.JTextField Box_5;
    private javax.swing.JTextField Box_6;
    private javax.swing.JTextField Box_7;
    private javax.swing.JTextField Box_8;
    private javax.swing.JTextField Box_9;
    private javax.swing.JTextField Timer_Minute;
    private javax.swing.JTextField Timer_Second;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
